"""Initial migration

Revision ID: bdc4af93e5e9
Revises: 
Create Date: 2025-08-17 23:03:05.369169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bdc4af93e5e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
    op.drop_index(op.f('email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('expenses', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
    # ### end Alembic commands ###
